name: Node.js TypeScript Build and Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and Test Project
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project
      uses: actions/checkout@v3
      
    - name: Setup Node
      uses: actions/setup-node@v3
      
    - name: Install Packages
      run: npm i
      
    - name: Build From TypeScript
      run: npm run build
      
    - name: Run Tests
      run: npm test
